config:
  install_hash_length: 8
  install_tree:
    root: $spack/opt/spack
    projections:
      all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:8}
  module_roots:
    tcl: $spack/share/spack/modules
    lmod: $spack/share/spack/lmod
  build_stage:
  - $spack/var/spack/stage
  # Use single source cache per user to avoid unnecessary downloading across spack installations
  source_cache: ~/.spack/downloads
  misc_cache: ~/.spack/cache
  verify_ssl: true
  checksum: true
  dirty: false
  locks: false
  build_jobs: 18
